name: dist
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: make
    - run: find dist
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
