name: dist

on:
  push:
    branches-ignore:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ./check.sh
    - run: npm config set @riza-io:registry https://npm.pkg.riza.io
    - run: npm install
    - run: make
    - run: find dist
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
